apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - telemetry-service.yaml
  - telemetry-deployment.yaml

images:
  - name: acrdevtodoacr.azurecr.io/telemetry
    newTag: v3        # CI isko har build par replace karega