apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-deployment
  template:
    metadata:
      labels:
        app: telemetry-deployment
    spec:
      containers:
      - name: tele-con
        image: acrdevtodoacr.azurecr.io/telemetry:CI_IMAGE_TAG
        # ^ CI pipeline is tag ko git short-SHA se replace karega
        #   pehli baar manually kisi valid tag se replace kar dena (jo already ACR me pushed ho)
        ports:
        - containerPort: 8000